pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    cd server/src/main/resources
    sed -i "s/dbserver/$SERVER/g" application.properties
    sed -i "s/dblogin/$LOGIN/g" application.properties
    sed -i "s/dbpassword/$PASSWORD/g" application.properties
    sed -i "s/jwtsecret/$SECRET/g" application.properties
    cd ../../../
    chmod +x ./mvnw
    ./mvnw clean package
    mv target/server-0.1.0.jar target/app.jar
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(68cb8e64-267d-4914-9259-cdaca456d096)'
    appType: 'webApp'
    appName: 'hobbymeetingappserver'
    deployToSlotOrASE: true
    resourceGroupName: 'maven-plugin'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/server/target/*.jar'
    customWebConfig: